import type { Career } from '@/types';

export const CAREERS: Career[] = [
  {
    id: 'siksu',
    company: '식수대장',
    role: 'Freelance Lead Developer',
    period: { start: '2025.09', end: '2026.01' },
    domain: 'saas',
    summary: 'QR 기반 기업 식수 관리 SaaS를 1인 풀스택으로 설계, 개발, 운영했습니다.',
    highlights: [
      'Flutter 사용자 앱과 파트너 앱, React 어드민 웹, FastAPI/MariaDB 백엔드를 단독 구축',
      'QR 인증 기반 실시간 자동 식수 기록으로 수기 체크 대비 처리 시간을 50% 이상 단축',
      'BLoC와 Clean Architecture를 도입해 UI와 비즈니스 로직을 분리하고 개발 효율을 개선',
      'Docker 컨테이너 기반 배포 구조를 마련해 운영 중 버그 패치 안정성을 확보',
    ],
    stack: ['Flutter', 'React', 'TypeScript', 'FastAPI', 'MariaDB', 'Docker', 'BLoC'],
  },
  {
    id: 'naviai',
    company: '나비에이아이',
    role: 'Android / AI Developer',
    period: { start: '2023.09', end: '2025.08' },
    domain: 'ai',
    summary: '신규 네이티브 앱 아키텍처와 AI/컴퓨터 비전 PoC를 담당했습니다.',
    highlights: [
      'MoonShot, Buzzbit Android 앱의 MVVM 기반 메인 아키텍처 설계 및 Google Play 론칭',
      'Telegram Bot API 기반 긴급 CS 자동화 채널을 구축해 응대 시간을 약 50% 단축',
      'Google Vertex AI와 YOLO를 활용한 실시간 낙상 감지 기술 검증을 완료',
    ],
    stack: ['Kotlin', 'Android', 'MVVM', 'LiveData', 'Telegram Bot API', 'Vertex AI', 'YOLO'],
  },
  {
    id: 'meeples',
    company: '미플즈',
    role: 'Senior Android Freelancer',
    period: { start: '2023.01', end: '2023.05' },
    domain: 'app',
    summary: '하이브리드 오더 앱을 Android Native Kotlin 앱으로 전환했습니다.',
    highlights: [
      '하이브리드 코드베이스를 5개월 내 Kotlin Native 구조로 100% 재구축',
      'Google Maps API와 OCR 모듈을 단독 탑재하고 레거시 구조를 안정화',
    ],
    stack: ['Kotlin', 'Android Native', 'Google Maps API', 'OCR'],
  },
  {
    id: 'ubivelox',
    company: '유비벨록스',
    role: 'Senior Android IVI Developer',
    period: { start: '2022.07', end: '2022.12' },
    domain: 'automotive',
    summary: 'Ford 차량용 Android IVI 시스템과 내비게이션 모듈 연동을 개발했습니다.',
    highlights: [
      'Ford 양산 차량 대상 Android 인포테인먼트 시스템 개발에 기여',
      'Bluetooth 연동 프로토콜을 최적화해 하드웨어와 소프트웨어 응답 안정성을 확보',
    ],
    stack: ['Android IVI', 'Kotlin', 'Bluetooth', 'Navigation'],
  },
  {
    id: 'newlink',
    company: '뉴링크',
    role: 'Android Developer',
    period: { start: '2019.08', end: '2022.01' },
    domain: 'exchange',
    summary: '디지털 자산 거래소 앱의 Android 고도화와 iOS 유지보수를 병행했습니다.',
    highlights: [
      '구형 Java 대형 레거시 프로젝트를 Kotlin 환경으로 100% 전환',
      'FaceID, 카카오/애플 OAuth 등 금융 인증 보안 기능을 탑재',
      'FCM 기반 암호화폐 매수/매도 실시간 푸시 알림 인프라를 고도화',
      'iOS 개발자 공백 기간 Swift 앱 유지보수까지 병행해 서비스 운영을 지속',
    ],
    stack: ['Kotlin', 'Java', 'Swift', 'OAuth', 'FaceID', 'FCM'],
  },
  {
    id: 'hanpass',
    company: '한패스',
    role: 'Android Developer',
    period: { start: '2018.03', end: '2019.08' },
    domain: 'fintech',
    summary: '글로벌 송금·환전 Android 앱과 다국어 운영 모듈을 개발했습니다.',
    highlights: [
      '해외 송금·환전 Android 앱 핵심 설계와 서비스 운영에 기여',
      '20개국 이상 언어 대응 관리 모듈을 단독 구현',
      'Google Apps Script 기반 업무 자동화와 모니터링 배치를 구축',
    ],
    stack: ['Kotlin', 'Android', 'Fintech', 'Google Apps Script'],
  },
];

export const OTHER_CAREERS: Career[] = [
  {
    id: 'spidercraft',
    company: '스파이더크래프트',
    role: 'Senior Android Developer',
    period: { start: '2022.02', end: '2022.05' },
    domain: 'service',
    summary: '배달기사 앱 유지보수와 기기 보안 알고리즘을 담당했습니다.',
    highlights: [
      'PackageManager 기반 유해 앱 탐지 알고리즘 설계',
      'Firebase Remote Config 기반 원격 보안 트리거 시스템 구축',
    ],
    stack: ['Kotlin', 'PackageManager', 'Firebase Remote Config'],
  },
  {
    id: 'revolution',
    company: '레볼루션',
    role: 'Android Developer',
    period: { start: '2016.05', end: '2017.05' },
    domain: 'app',
    summary: 'SI 파견 Android 앱의 초기 구조와 개발 가이드라인을 수립했습니다.',
    highlights: ['Notification 앱 신규 개발', 'LG IoT 앱 개발 참여'],
    stack: ['Android', 'Java'],
  },
  {
    id: 'worldpga',
    company: '월드피지에이',
    role: 'Android Developer',
    period: { start: '2015.09', end: '2016.04' },
    domain: 'app',
    summary: '골프 위치 정보와 스코어 연동 서비스 앱을 유지보수했습니다.',
    highlights: ['골프 통합 앱 론칭 기여', 'SQLite DB 인덱싱 튜닝으로 조회 성능 개선'],
    stack: ['Android', 'Java', 'SQLite'],
  },
  {
    id: 'dreambean',
    company: '드림빈',
    role: 'Android Developer',
    period: { start: '2014.12', end: '2015.03' },
    domain: 'app',
    summary: '실시간 프로필 매칭 소개팅 Native 앱을 개발하고 배포했습니다.',
    highlights: ['Native Android 앱 단독 개발', 'Google Play 배포 완료'],
    stack: ['Android', 'Java', 'Google Play'],
  },
];
